# Generated by Django 3.1.2 on 2021-07-09 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cognito_auth_layer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cognitouserjwt',
            name='cognito_aut_usernam_814415_idx',
        ),
        migrations.RemoveField(
            model_name='cognitouserjwt',
            name='username',
        ),
        migrations.AddField(
            model_name='cognitouserjwt',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.user', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cognitouserjwt',
            index=models.Index(fields=['email'], name='cognito_aut_email_i_635721_idx'),
        ),
    ]
