# product types
PRODUCT_TYPE_ADS_PACKAGE = "ADS PACKAGE"
PRODUCT_TYPE_ADD_ON = "ADD-ON"


# attribute names
ATTRIBUTE_DURATION = "DURATION"
ATTRIBUTE_NUMBER_OF_ADS = "NUMBER OF ADS"
ATTRIBUTE_DISPLAY_NAME = "DISPLAY NAME"


# duration values
DURATION_1_DAY = "1-DAY"
DURATION_1_WEEK = "1-WEEK"
DURATION_1_MONTH = "1-MONTH"
DURATION_6_MONTH = "6-MONTH"
DURATION_1_YEAR = "1-YEAR"


# number of ads values
NUMBER_OF_ADS_UNLIMITED = "UNLIMITED"
NUMBER_OF_ADS_1 = "1"

# add-on duration values
ADD_ON_DURATION_3_DAY = "3-DAY"
ADD_ON_DURATION_UNLIMITED = "UNLIMITED"

# add-on types
ADD_ON_PREMIUM = "PREMIUM"
ADD_ON_MYWHEELS_FEATURE = "MYWHEELS FEATURE"
ADD_ON_MYWHEELS_FB_POST = "MYWHEELS FACEBOOK POST"
ADD_ON_MYWHEELS_FB_PIN = "MYWHEELS FACEBOOK PIN"
ADD_ON_CP_REGIONAL_FEATURE = "CP REGIONAL FEATURE"
ADD_ON_CP_REGIONAL_FB = "CP REGIONAL FACEBOOK"
ADD_ON_CP_REGIONAL_FB_PIN = "CP REGIONAL FACEBOOK PIN"


# region values
ADD_ON_REGION_EAST = "EAST"
ADD_ON_REGION_NORTH = "NORTH"
ADD_ON_REGION_JHR = "JHR"
ADD_ON_REGION_KUL = "KUL"
ADD_ON_REGION_MLK = "MLK"
ADD_ON_REGION_NSN = "NSN"
ADD_ON_REGION_PRK = "PRK"
ADD_ON_REGION_MYWHEELS = "MYWHEELS"


# constant values for django API integration purposes
# add on type enum defined on django server
DJANGO_ENUM_ADD_ON_PREMIUM = "PREMIUM"
DJANGO_ENUM_ADD_ON_FEATURED = "FEATURED"
DJANGO_ENUM_ADD_ON_FB_POST = "FB_POST"
DJANGO_ENUM_ADD_ON_FB_PIN = "FB_PIN"


# add on duration enum defined on django server
DJANGO_ENUM_ADD_ON_THREE_DAY = "3"
DJANGO_ENUM_ADD_ON_UNLIMITED = None
